name: 'Build and Push Docker Image'
description: 'Builds a Docker image with caching and pushes it to Amazon ECR'

inputs:
  ecr-registry:
    description: 'The Amazon ECR registry'
    required: true
  ecr-name:
    description: 'The name of the ECR repository'
    required: true
  version:
    description: 'The version tag for the Docker image'
    required: true

outputs:
  version:
    description: 'The version of the built image'
    value: ${{ steps.docker_meta.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.ecr-registry }}/${{ inputs.ecr-name }}
        flavor: |
          latest=false
        tags: |
          type=raw,value=${{ inputs.version }}

    - name: Print Version
      shell: bash
      run: |
        echo "Version ${{ steps.docker_meta.outputs.version }}"

    - name: Build, tag, and push image to Amazon ECR
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        provenance: false
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        build-args: |
          V=${{ steps.docker_meta.outputs.version }}

    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache