name: Read Gradle version
description: Read the version property from a gradle.properties file

outputs:
  value:
    description: 'Version from gradle.properties'
    value: ${{ steps.gradle_version.outputs.value }}


runs:
  using: "composite"
  steps:
    - id: gradle_version
      shell: bash
      run: |
        value=$(grep -E "^version=" "gradle.properties" | cut -d'=' -f2- | tr -d '\r' | xargs)
        echo "value=$value" >> $GITHUB_OUTPUT
