name: Deploy to DEV

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Calculate Version with Git Hash
        id: full_version
        uses: ./.github/actions/extract-version
        with:
          is_beta: true

      - run: echo "Combined version is ${{ steps.full_version.outputs.version }}"
