name: Deploy to DEV

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Calculate Version with Git Hash
        id: full_version
        uses: ./.github/actions/extract-version
        with:
          is_beta: true

      - run: echo "Combined version is ${{ steps.full_version.outputs.version }}"

  deploy-to-dev:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit
    with:
      env: "dev"
      version: ${{ needs.extract-version.outputs.version }}
      primary_region: eu-north-1
      secondary_regions: '["us-west-2"]'
      cluster_name: dev-qbneuron
      service_name: dev-qbneuron-nexus
      e2e_event_name: dev-qbneuron-tests