name: Deploy to Development Environment

on:
#  push:
#    branches: [ develop ]
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Gradle Version
        id: read
        uses: ./.github/actions/extract-version

      - name: Get Git Hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Combine Version and Hash
        id: combined
        run: echo "version=${{ steps.read.outputs.version }}-${{ steps.hash.outputs.hash }}" >> $GITHUB_OUTPUT

      - run: echo "Combined version is ${{ steps.combined.outputs.version }}"