name: Deploy to Staging Environment

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy-to-stage:
    if: github.event_name == 'release' && github.event.release.target_commitish == 'release/${{github.ref_name}}'
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit
    with:
      env: "stage"
      primary_region: eu-north-1
      secondary_regions: '["us-west-2"]'
      cluster_name: stage-qbneuron
      service_name: stage-qbneuron-nexus
      e2e_event_name: stage-qbneuron-tests