name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Gradle Version
        id: read
        uses: ./.github/actions/extract-version

      - run: echo "Project version is ${{ steps.read.outputs.version }}"

  branch-and-tag:
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - run: echo "Releasing version ${{ needs.extract-version.outputs.version }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/create-branch-and-tag
        with:
          version: ${{ needs.extract-version.outputs.version }}

  build-image:
    runs-on: ubuntu-latest
    needs: [extract-version, branch-and-tag]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.branch-and-tag.outputs.branch_name }}
          fetch-depth: 0

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          echo "Logging in to Amazon ECR..."

      - name: Build and push Docker image
        id: build_and_push
        run: |
            echo "Building and pushing Docker image version ${{ needs.extract-version.outputs.version }}"

  deploy-stage:
    name: Deploy to ECS (STAGE)
    runs-on: ubuntu-latest
    needs: [extract-version, build-image]
    environment: staging

    steps:
      - name: Update ECS service (staging)
        run: |
          echo "Deploying version ${{ needs.extract-version.outputs.version }} to staging"

  report-release-stage:
    name: Report Release on stage
    runs-on: ubuntu-latest
    needs: [extract-version, deploy-stage]
    steps:
      - name: Report release
        shell: bash
        run: |
          echo ${{ github.actor }} released version ${{ needs.extract-version.outputs.version }} of ${{ github.repository }}

  deploy-prod:
    name: Deploy to ECS (PROD)
    runs-on: ubuntu-latest
    needs: [extract-version, deploy-stage]
    environment:
      name: production
      url: https://clinic.qbtech.com

    steps:
      - name: Update ECS service (PROD)
        run: |
            echo "Deploying version ${{ needs.extract-version.outputs.version }} to production"

  report-release-prod:
    name: Report Release on prod
    runs-on: ubuntu-latest
    needs: [extract-version, deploy-prod]
    steps:
      - name: Report release
        shell: bash
        run: |
          echo ${{ github.actor }} released version ${{ needs.extract-version.outputs.version }} of ${{ github.repository }}