name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Gradle Version
        id: read
        uses: ./.github/actions/extract-version

      - run: echo "Project version is ${{ steps.read.outputs.version }}"

  branch-and-tag:
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - run: echo "Releasing version ${{ needs.extract-version.outputs.version }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/create-branch-and-tag
        with:
          version: ${{ needs.extract-version.outputs.version }}

  build-image:
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          echo "Logging in to Amazon ECR..."

      - name: Build and push Docker image
        id: build_and_push
        run: |
            echo "Building and pushing Docker image version ${{ needs.extract-version.outputs.version }}"

  deploy-stage:
    name: Deploy to ECS (STAGE)
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: staging

    steps:
      - name: Update ECS service (staging)
        run: |
          echo "Deploying version ${{ needs.extract-version.outputs.version }} to staging"

  deploy-prod:
    name: Deploy to ECS (PROD)
    runs-on: ubuntu-latest
    needs: deploy_staging
    environment:
      name: production
      url: https://clinic.qbtech.com
      # 👇 this triggers manual approval before this job runs
      # Configure this in your repo Settings → Environments → production → Required reviewers

    steps:
      - name: Update ECS service (PROD)
        run: |
            echo "Deploying version ${{ needs.extract-version.outputs.version }} to production"